### ISSUE TITLE
overwrite check for generated png

### ISSUE THREAD

**Issue by TimFFischer** [lejmr/dokuwiki-plugin-drawio#24] opened 2020-04-23 01:14 UTC
as far as I understood the plugin a png with the given name in the brackets is generated.
I have not seen an overwrite check, when this picture is already existing (when used first).

**Comment by lejmr** [comment] 2020-04-26 10:05
when you specify an already used name then the already created images is embeded into the page. Subsequently, the user sees the already existing image hence must decide whetner want to modify the image or use another image name..

Therefore, this problem is solved itself by design. I am closing this ticket.

**Closed by lejmr** 2020-04-26 10:05 UTC
