### ISSUE TITLE
Page show only placeholder of image

### ISSUE THREAD

**Issue by stefanfink** [lejmr/dokuwiki-plugin-drawio#1] opened 2019-10-22 07:50 UTC
When I use the DrawIO plugin, the png image of the drawIO flowchart is shown as placeholder of the real image.
In the Mediamanager I see the real image.
When I create an PDF with the Dw2Pdf plugin everything is perfectly shown.
When I click on the placeholder, the DrawIO program will be shown (perfect) with the real flowchart inside. When I click on Save the Page will be actualized and the Image is perfectly shown.
When I click on Exit the Placeholder will be shown.
I use the last Dokuwiki upgrade and a lot of Plugins

**Comment by guillaumv** [comment] 2019-10-28 19:58
Hi,

First thanky you for doing this most awaited plugin. I am very grateful!

However I cannot use it, I have installed it with the extension manager and it went well (except that it says that there is an update when it seems there is none).

maybe I dont understand the instruction but when I put :
{{drawio>testimage}} in my page nothing shows up. I mean no image to click on. As if the plugin didnt install (but it did).

I am using Greebo on apache2.

Any idea?

**Comment by Juergen-aus-Koeln** [comment] 2019-10-29 12:12
Hi,

the idea of the plugin is very good, and I have searched for something like this for a long time!

But I have the same problem as StefanFink. 

And one more: If I define a link inside an element of the flowshart this link has no effect in the wiki page, because the click into the shart always opens the draw.io-editor

Best regards
Juergen

**Comment by CubaLibre84** [comment] 2019-11-04 13:38
Hi,

First, thank you for the great plugin!

Reply to:
> " in my page nothing shows up. I mean no image to click on."

In Microsoft Edge, I also observed, that there is no small image displayed.
In Firefox I see the placeholder image, but when I click on it, I only see "Loading..." and the menu bar of the editor but everything else is GRAYED OUT. So it is not possible to draw any shape and save it.

Does anyone know what the issue could be? Thanks in advance!

**Comment by CubaLibre84** [comment] 2019-11-13 11:42
Hi. Can someone please push the project forward? I urgently need this plugin!

**Comment by todag** [comment] 2019-11-13 12:40
> Hi. Can someone please push the project forward? I urgently need this plugin!

I also need this plugin urgently.

I have started development of my own plugin (based on this one) primarily to enable offline use (Draw.io is bundled in my plugin).

I currently have support for ACL’s and Media Manager revisions + a few fixes for other issues.

I'll try to publish something this week, either as a pull request to this one or as a separate plugin.

**Comment by chrisisbd** [comment] 2019-12-29 17:42
I'm running the drawio plugin in Dokowiki "Greebo" on an xubuntu 19.04 system.  It works brilliantly and is perfect for drawing network diagrams, flowcharts, etc.  Thank you!

However I do have the same/similar problem to those noted above.  When I first open the page where I have placed {{drawio>:lan}} all I ever see is the little placeholder box with a tiny grey image in it.  Clicking on this opens the drawio diagram editor, then when I click on Save I get to see the wiki page with the diagram.  However if I leave the page and come back I have to click on the little box again....

**Comment by lejmr** [comment] 2019-12-30 11:35
Hey guys,

I see there is quite a few of you having this same issue. Can you please provide me information how are you using this plugin? 
* HTTP server
* HTTP server configuration
* Web browser and its version

Any idea how to reproduce this issue? Without that I cant replicate this bug. Ideally, send me instructions how to replicate this problem.

**Comment by chrisisbd** [comment] 2019-12-30 12:08
I thought I had left a further comment after saying I had the same problem but it seems to have disappeared.  I followed someone else's comment which had a fix (though, as they said, it was a bit clumsy).  I have now fixed the problem on my system by changing syntax.php as follows:-

the statement
```

        $renderer->doc .= "<img class='mediacenter' id='".trim($data)."'  
                        style='max-width:100%;cursor:pointer;'  
                        onclick='edit(this);'  
                        src='lib/exe/fetch.php?media=".$data.".png'  
                        alt='".$file_name."' />";
```

should be

```
        $renderer->doc .= "<img class='mediacenter' id='".trim($data)."'  
                        style='max-width:100%;cursor:pointer;'  
                        onclick='edit(this);'  
                        src='".DOKU_BASE."lib/exe/fetch.php?media=".$data.".png'  
                        alt='".$file_name."' />";
```


Oh, and another little quirk, you must remove the colon (:) from the {{drawio>lan}}
where 'lan' is the filename.  If you put {{drawio>:lan}} then you get symptoms rather like those above because some parts of Dokuwiki remove the colon and others don't.

**Comment by lejmr** [comment] 2019-12-30 17:31
Merged your code changes

**Comment by CubaLibre84** [comment] 2020-01-02 14:15
I'd like to come back to this comment:
(the editor is stuck when loading the image)

> maybe I dont understand the instruction but when I put :
> {{drawio>testimage}} in my page nothing shows up. I mean no image to click on. As if the plugin > didnt install (but it did).

In this case, the web browser will display a symbol of a non-existing image, which is not the icon.png provided by the plugin. As you click on this 'image', the ajax request will fail: 

> script.js line 59:   "DOKU_BASE + 'lib/exe/ajax.php',  call: 'plugin_drawio', ...")

because this line can't find the image:
> action.php line 83: echo $json->encode(array("content" => "data:image/png;base64,".base64_encode($fc)));

I added the following lines of code (after line 62 in action.php) to copy the actual placeholder image file:
>            $image_file = $name.'.png';
>            $file_path = "/".join("/", array(trim($media_dir, "/"), $image_file));
>            if (! file_exists($file_path)) {
>            	copy(DOKU_PLUGIN.'/drawio/icon.png', $file_path);
>            }

I have no idea if this is the best way to fix this problem. But at least the editor starts now correctly. 
 Another possibility is to upload the png file manually via the media manager. But then the documentation needs to be updated:
> Then an default image is depicted into the page, so feel free and click onto the image in order to open Draw.io integration editor.

**Comment by guillaumv** [comment] 2020-01-02 14:34
Thanks for the suggestions, but my situation is even weirder...

I write a page with this : 

> Bienvenue!
> 
> {{drawio>testimage3}}
> 
> some text here


and I see that on chrome :

![image](https://user-images.githubusercontent.com/56190302/71671933-b0917380-2d74-11ea-8158-6df336140e41.png)

I really have no idea of where to start to investigate I must say. I will keep searching but any hint would help.

**Comment by CubaLibre84** [comment] 2020-01-02 15:18
Hi. please try a different browser (I use Firefox and the icon is displayed).
Maybe this will help:
https://windowsreport.com/quick-fix-google-chrome-broken-image-icon-error/

And for the developer, the following might me be interesting:
https://css-tricks.com/snippets/jquery/better-broken-image-handling/

**Comment by guillaumv** [comment] 2020-01-02 15:46
Thank you very much !
it works fine on firefox. my users are on chrome so it is still a problem but at least we know which one!

**Comment by lejmr** [comment] 2020-01-02 15:49
Indeed this can be an issue in some browsers. IDK as I am a firefox user where I get an system-fallback image, so I have got an idea there is something missing hence I sense to click somewhere..

The simple solution would be to provide an .png file into the plugin home folder. Will try to implement it.

**Comment by lejmr** [comment] 2020-01-04 15:49
I have just added this functionality into verion 0.2.2

**Comment by lejmr** [comment] 2020-01-04 15:50
Will close this ticket, but if you find it buggy feel free to open a bug ticket

**Closed by lejmr** 2020-01-04 15:50 UTC
